// Ohio Veterans — Navigator
// All 88 Ohio counties, plus the full CVSO office directory (office name,
// address, phone, email, website) for every county — sourced from the real
// ODVS "Find your CVSO" directory (https://dvs.ohio.gov/resources-for-veterans/find-your-cvso).

export const OHIO_COUNTIES = [
  'Adams', 'Allen', 'Ashland', 'Ashtabula', 'Athens', 'Auglaize', 'Belmont',
  'Brown', 'Butler', 'Carroll', 'Champaign', 'Clark', 'Clermont', 'Clinton',
  'Columbiana', 'Coshocton', 'Crawford', 'Cuyahoga', 'Darke', 'Defiance',
  'Delaware', 'Erie', 'Fairfield', 'Fayette', 'Franklin', 'Fulton', 'Gallia',
  'Geauga', 'Greene', 'Guernsey', 'Hamilton', 'Hancock', 'Hardin', 'Harrison',
  'Henry', 'Highland', 'Hocking', 'Holmes', 'Huron', 'Jackson', 'Jefferson',
  'Knox', 'Lake', 'Lawrence', 'Licking', 'Logan', 'Lorain', 'Lucas', 'Madison',
  'Mahoning', 'Marion', 'Medina', 'Meigs', 'Mercer', 'Miami', 'Monroe',
  'Montgomery', 'Morgan', 'Morrow', 'Muskingum', 'Noble', 'Ottawa', 'Paulding',
  'Perry', 'Pickaway', 'Pike', 'Portage', 'Preble', 'Putnam', 'Richland',
  'Ross', 'Sandusky', 'Scioto', 'Seneca', 'Shelby', 'Stark', 'Summit',
  'Trumbull', 'Tuscarawas', 'Union', 'Van Wert', 'Vinton', 'Warren',
  'Washington', 'Wayne', 'Williams', 'Wood', 'Wyandot',
];

export const NOT_IN_OHIO = 'not-in-ohio';

export const COUNTY_SELECT_OPTIONS = [
  ...OHIO_COUNTIES.map((name) => ({ value: name, label: `${name} County` })),
  { value: NOT_IN_OHIO, label: "Not sure / I don't live in Ohio yet" },
];

// Real CVSO office directory for all 88 Ohio counties.
export const CVSO_DIRECTORY = {
  Adams: {
    officeName: 'Adams County Veterans Service Office',
    address: '923 Sunrise Ave., Room 102, West Union, OH 45693',
    phone: '1 (937) 544-7857',
    email: 'russell.todd@adamscountyoh.gov',
    website: 'https://www.adamscountyoh.gov/adams-county-veterans-service-office/',
  },
  Allen: {
    officeName: 'Allen County Veterans Service Office',
    address: '301 N. Main St., Room 113, Lima, OH 45801',
    phone: '1 (419) 223-8522',
    email: 'acvso@allencountyohio.com',
    website: 'https://www.allencountyvsc.com/',
  },
  Ashland: {
    officeName: 'Ashland County Veterans Service Office',
    address: '110 Cottage St., Ashland, OH 44805',
    phone: '1 (419) 282-4225',
    email: 'veterans@ashlandcounty.org',
    website: 'https://ashlandcountyveteransohio.org/',
  },
  Ashtabula: {
    officeName: 'Ashtabula County Veterans Service Office',
    address: '1709 E. Prospect Rd., Ashtabula, OH 44004',
    phone: '1 (440) 964-8324',
    email: 'ACVSC@ashtabulacounty.us',
    website: 'http://ashtabulaveterans.com',
  },
  Athens: {
    officeName: 'Athens County Veterans Service Office',
    address: '88 N. Plains Rd., Ste. 102, The Plains, OH 45780',
    phone: '1 (740) 592-3216',
    email: 'kspencer@athensoh.org',
    website: 'https://www.athensveteransservicesoh.org',
  },
  Auglaize: {
    officeName: 'Auglaize County Veterans Service Office',
    address: '209 S. Blackhoof St., Room 202, Wapakoneta, OH 45895',
    phone: '1 (419) 739-6750',
    email: 'veterans@auglaizecounty.org',
    website: 'https://www.augvsc.org',
  },
  Belmont: {
    officeName: 'Belmont County Veterans Service Office',
    address: '400 Imperial Plaza, Bellaire, OH 43906',
    phone: '1 (740) 325-1042',
    email: 'cindy@belmontcountyveterans.org',
    website: 'https://www.belmontcountyveterans.org/',
  },
  Brown: {
    officeName: 'Brown County Veterans Service Office',
    address: '826 Mt. Orab Pike, Georgetown, OH 45121',
    phone: '1 (937) 378-3155',
    email: 'Kcrank@browncountyohio.gov',
    website: 'http://www.browncountyohio.gov/index.php/veterans-services',
  },
  Butler: {
    officeName: 'Butler County Veterans Service Office',
    address: 'Butler County Gov. Service Ctr., 315 High St., 1st Flr., Hamilton, OH 45011',
    phone: '1 (513) 887-3600',
    email: 'vsc@butlercountyohio.org',
    website: 'http://www.bcvets.org/',
  },
  Carroll: {
    officeName: 'Carroll County Veterans Service Office',
    address: '160 Second St. SW, P.O. Box 303, Carrollton, OH 44615',
    phone: '1 (330) 627-2590',
    email: 'vsocblack@yahoo.com',
    website: 'https://carrollcountyohio.us/agencies-and-departments/veteran-service-office/',
  },
  Champaign: {
    officeName: 'Champaign County Veterans Service Office',
    address: '220 E. Court St., Urbana, OH 43078',
    phone: '1 (937) 653-4554',
    email: 'champvso@co.champaign.oh.us',
    website: 'https://www.co.champaign.oh.us/Veterans/index.html',
  },
  Clark: {
    officeName: 'Clark County Veterans Service Office',
    address: '117 S. Fountain Ave., Springfield, OH 45502',
    phone: '1 (937) 521-2030',
    email: 'veterans@clarkcountyohio.gov',
    website: 'https://veteransofclarkcountyohio.com/',
  },
  Clermont: {
    officeName: 'Clermont County Veterans Service Office',
    address: '76 S. Riverside Dr., Heritage Bldg., 3rd Flr., Batavia, OH 45103',
    phone: '1 (513) 732-7363',
    email: 'sbalczo@clermontcountyveterans.com',
    website: 'http://www.clermontcountyveterans.com/',
  },
  Clinton: {
    officeName: 'Clinton County Veterans Service Office',
    address: '43 S. Walnut St., Box #2, Wilmington, OH 45177',
    phone: '1 (937) 382-3233',
    email: 'vets@clintoncountyohio.us',
    website: 'https://www.clintonvets.com/',
  },
  Columbiana: {
    officeName: 'Columbiana County Veterans Service Office',
    address: '7989 Dickey Dr., Ste. 1, Lisbon, OH 44432',
    phone: '1 (330) 424-7214',
    email: 'dsmith@columbianacountyvsc.org',
    website: 'https://columbianacountyvets.org/',
  },
  Coshocton: {
    officeName: 'Coshocton County Veterans Service Office',
    address: 'Courthouse, 318 Main St., Coshocton, OH 43812',
    phone: '1 (740) 622-2313',
    email: 'dougschaefer@coshoctoncounty.net',
    website: 'https://www.coshoctoncounty.net/veterans/',
  },
  Crawford: {
    officeName: 'Crawford County Veterans Service Office',
    address: '112 E. Mansfield St., Ste. 95, CH Lower Level, Admin. Bldg., Bucyrus, OH 44820',
    phone: '1 (419) 562-7761',
    email: 'mikea@crawford-co.org',
    website: 'http://www.crawfordcountyveteransohio.com/',
  },
  Cuyahoga: {
    officeName: 'Cuyahoga County Veterans Service Office',
    address: '3950 Chester Ave., Cleveland, OH 44114',
    phone: '1 (216) 698-2600',
    email: 'vscmail@cuyahogacounty.us',
    website: 'http://cuyahogavets.org/',
  },
  Darke: {
    officeName: 'Darke County Veterans Service Office',
    address: '611 Wagner Ave., Greenville, OH 45331',
    phone: '1 (937) 548-5305',
    email: 'tpitman@darkecountyveterans.org',
    website: 'https://darkecountyveterans.org/',
  },
  Defiance: {
    officeName: 'Defiance County Veterans Service Office',
    address: '1300 E. Second St., Ste. 102, Defiance, OH 43512',
    phone: '1 (419) 782-6861',
    email: 'veterans@defiance-county.com',
    website: 'https://www.defiance-county.com//veterans-affairs/index.php',
  },
  Delaware: {
    officeName: 'Delaware County Veterans Service Office',
    address: '91 N. Sandusky St., Delaware, OH 43015',
    phone: '1 (740) 833-2010',
    email: 'bgalligher@co.delaware.oh.us',
    website: 'https://veteransservice.co.delaware.oh.us/',
  },
  Erie: {
    officeName: 'Erie County Veterans Service Office',
    address: '2900 Columbus Ave., 2nd Flr., Sandusky, OH 44870',
    phone: '1 (419) 627-7650',
    email: 'csolander@eriecounty.oh.gov',
    website: 'https://www.eriecounty.oh.gov/Veteransresources.aspx',
  },
  Fairfield: {
    officeName: 'Fairfield County Veterans Service Office',
    address: '1550 Sheridan Dr., Ste. 301, Lancaster, OH 43130',
    phone: '1 (740) 652-7920',
    email: 'Justin.messinger@fairfieldcountyohio.gov',
    website: 'https://www.fcvsc.org/',
  },
  Fayette: {
    officeName: 'Fayette County Veterans Service Office',
    address: '133 S. Main St., Ste. L11, Washington Court House, OH 43160',
    phone: '1 (740) 335-1610',
    email: 'vetsservices@fayette-co-oh.com',
    website: 'https://www.fayette-co-oh.com/253/Veterans-Service-Commission',
  },
  Franklin: {
    officeName: 'Franklin County Veterans Service Office',
    address: '280 E. Broad St., 1st Flr., Columbus, OH 43215',
    phone: '1 (614) 525-2500',
    email: 'veteransservice@franklincountyohio.gov',
    website: 'https://vets.franklincountyohio.gov/',
  },
  Fulton: {
    officeName: 'Fulton County Veterans Service Office',
    address: '604 S. Shoop Ave., Ste. 270, Wauseon, OH 43567',
    phone: '1 (419) 337-9266',
    email: 'fcvets@fultoncountyoh.com',
    website: 'https://www.fultoncountyoh.com/1387/Veterans-Services',
  },
  Gallia: {
    officeName: 'Gallia County Veterans Service Office',
    address: '323 Upper River Rd., Ste. A, Gallipolis, OH 45631',
    phone: '1 (740) 446-2005',
    email: 'jdanford@gallianet.net',
    website: 'https://galliacountyoh.gov/veterans/',
  },
  Geauga: {
    officeName: 'Geauga County Veterans Service Office',
    address: '12611 Ravenwood Dr., Ste. 260, Chardon, OH 44024',
    phone: '1 (440) 279-1860',
    email: 'mpemberton@co.geauga.oh.us',
    website: 'https://vets.co.geauga.oh.us/',
  },
  Greene: {
    officeName: 'Greene County Veterans Service Office',
    address: '571 Ledbetter Rd., Xenia, OH 45385',
    phone: '1 (937) 562-6020',
    email: 'timothy.espich@greenecountyohio.gov',
    website: 'https://greenevets.com/',
  },
  Guernsey: {
    officeName: 'Guernsey County Veterans Service Office',
    address: '627 Wheeling Ave., Ste. 102, Cambridge, OH 43725',
    phone: '1 (740) 432-9295',
    email: 'mliberatore@guernseycounty.org',
    website: 'https://guernseycounty.gov/veterans-services',
  },
  Hamilton: {
    officeName: 'Hamilton County Veterans Service Office',
    address: '1701 Patricia McCollum Way, Cincinnati, OH 45237',
    phone: '1 (513) 946-3300',
    email: 'glenn.welling@hamiltoncountyohio.gov',
    website: 'https://www.hcvsc.org/',
  },
  Hancock: {
    officeName: 'Hancock County Veterans Service Office',
    address: '401 Olive St., Findlay, OH 45840',
    phone: '1 (419) 424-7036',
    email: 'veterans@co.hancock.oh.us',
    website: 'http://hancockveterans.com/',
  },
  Hardin: {
    officeName: 'Hardin County Veterans Service Office',
    address: 'One Court House Sq., Ste. 120, Kenton, OH 43326',
    phone: '1 (419) 674-2219',
    email: 'vso@co.hardin.oh.us',
    website: 'http://www.hardinvets.com/',
  },
  Harrison: {
    officeName: 'Harrison County Veterans Service Office',
    address: 'Courthouse, 100 W. Market St., Cadiz, OH 43907',
    phone: '1 (740) 942-8441',
    email: 'plargent@harrisoncountyohio.org',
    website: 'https://www.harrisoncountyveteransservices.com/',
  },
  Henry: {
    officeName: 'Henry County Veterans Service Office',
    address: '1855 Oakwood Ave., Napoleon, OH 43545',
    phone: '1 (419) 592-0956',
    email: 'henrycovets@bright.net',
    website: 'https://www.henrycountyohio.gov/290/Veterans-Service-Commission',
  },
  Highland: {
    officeName: 'Highland County Veterans Service Office',
    address: '1575 N. High St., Ste. 400, Hillsboro, OH 45133',
    phone: '1 (937) 393-8686',
    email: 'highlandcountyvets@co.highland.oh.us',
    website: 'https://www.co.highland.oh.us/offices/veterans.html',
  },
  Hocking: {
    officeName: 'Hocking County Veterans Service Office',
    address: '30657 Redrock Ct., Logan, OH 43138',
    phone: '1 (740) 385-7507',
    email: 'vetsservice@co.hocking.oh.us',
    website: 'http://www.co.hocking.oh.us/veterans/',
  },
  Holmes: {
    officeName: 'Holmes County Veterans Service Office',
    address: '75 E. Clinton St., Ste. 104, Millersburg, OH 44654',
    phone: '1 (330) 674-4806',
    email: 'dstackhouse@co.holmes.oh.us',
    website: 'https://www.co.holmes.oh.us/veterans-services-overview',
  },
  Huron: {
    officeName: 'Huron County Veterans Service Office',
    address: '185 Shady Lane Dr., Ste. C, Norwalk, OH 44857',
    phone: '1 (419) 668-4150',
    email: 'info@huroncountyvets.com',
    website: 'https://www.huroncountyvets.com/',
  },
  Jackson: {
    officeName: 'Jackson County Veterans Service Office',
    address: '157 Broadway St., Jackson, OH 45640',
    phone: '1 (740) 286-3004',
    email: 'Scott.King@jacksoncountyveterans.com',
    website: 'http://www.jacksoncountyohio.us/boards-agencies/veterans-services/',
  },
  Jefferson: {
    officeName: 'Jefferson County Veterans Service Office',
    address: '500 Market St., Ste. 310, Steubenville, OH 43952',
    phone: '1 (740) 283-8571',
    email: 'SGlasure@JeffersonCountyOh.com',
    website: 'https://www.jeffersoncounty.vet',
  },
  Knox: {
    officeName: 'Knox County Veterans Service Office',
    address: '105 E. Chestnut St., Mt. Vernon, OH 43050',
    phone: '1 (740) 393-6742',
    email: 'kevinhenthorn@co.knox.oh.us',
    website: 'https://kcvso.com/',
  },
  Lake: {
    officeName: 'Lake County Veterans Service Office',
    address: 'Lake County Admin. Bldg., 105 Main St., Box 490, Painesville, OH 44077',
    phone: '1 (440) 350-2567',
    email: 'veteransservices@lakecountyohio.gov',
    website: 'https://www.lakecountyohio.gov/veteran-services/',
  },
  Lawrence: {
    officeName: 'Lawrence County Veterans Service Office',
    address: 'Courthouse, 111 S. Fourth St., Ironton, OH 45638',
    phone: '1 (740) 533-4327',
    email: 'lawcovets@lawrenceoh.com',
    website: 'https://lawcovets.org',
  },
  Licking: {
    officeName: 'Licking County Veterans Service Office',
    address: '935 Buckeye Ave., Newark, OH 43055',
    phone: '1 (740) 670-5430',
    email: 'afoster@lickingcounty.gov',
    website: 'https://lickingcounty.gov/depts/veterans/default.htm',
  },
  Logan: {
    officeName: 'Logan County Veterans Service Office',
    address: '121 S. Opera St., Memorial Hall, Bellefontaine, OH 43311',
    phone: '1 (937) 599-4221',
    email: 'veterans@logancountyohio.gov',
    website: 'https://www.logancountyohio.gov/veterans-services.html',
  },
  Lorain: {
    officeName: 'Lorain County Veterans Service Office',
    address: '1230 N. Abbe Rd., Elyria, OH 44035',
    phone: '1 (440) 284-4625',
    email: 'veterans@loraincounty.us',
    website: 'https://www.loraincountyveterans.com/',
  },
  Lucas: {
    officeName: 'Lucas County Veterans Service Office',
    address: '2555 Arlington Ave., Toledo, OH 43614',
    phone: '1 (419) 213-6090',
    email: 'LCVSC@co.lucas.oh.us',
    website: 'https://lucascountyvets.org/',
  },
  Madison: {
    officeName: 'Madison County Veterans Service Office',
    address: '1 N. Main St., Room 011, London, OH 43140',
    phone: '1 (740) 852-0676',
    email: 'jennifer.moore@madison.oh.gov',
    website: 'https://www.co.madison.oh.us/services/veteran_services/index.php',
  },
  Mahoning: {
    officeName: 'Mahoning County Veterans Service Office',
    address: '1915 Belmont Ave., Youngstown, OH 44504',
    phone: '1 (330) 740-2451',
    email: 'sskrzynski@mahoningcountyoh.gov',
    website: 'https://mahoningcountyvets.com/',
  },
  Marion: {
    officeName: 'Marion County Veterans Service Office',
    address: 'Veterans Memorial Coliseum, 220 E. Fairground St., Ste. 101, Marion, OH 43302',
    phone: '1 (740) 387-0100',
    email: 'bethmarion07@midohio.twcbc.com',
    website: 'http://www.marionveteranservice.com/',
  },
  Medina: {
    officeName: 'Medina County Veterans Service Office',
    address: '210 Northland Dr., Medina, OH 44256',
    phone: '1 (330) 722-9368',
    email: 'veterans@medinacountyveterans.org',
    website: 'https://www.medinacountyveteransoh.gov',
  },
  Meigs: {
    officeName: 'Meigs County Veterans Service Office',
    address: '115 E. Memorial Dr., Ste. A, Pomeroy, OH 45769',
    phone: '1 (740) 992-2820',
    email: 'meigscvso@hotmail.com',
    website: 'https://dvs.ohio.gov/static/cvso-resources/cvso-pdf-webpages/meigs-county-veterans-service-office.pdf',
  },
  Mercer: {
    officeName: 'Mercer County Veterans Service Office',
    address: '220 W. Livingston St., B270, Celina, OH 45822',
    phone: '1 (419) 586-3542',
    email: 'eric.pugh@veterans.mercercountyohio.gov',
    website: 'https://www.mercercountyohio.org/county-services/veteran-services/',
  },
  Miami: {
    officeName: 'Miami County Veterans Service Office',
    address: '510 W. Water St., Ste. 140, Troy, OH 45373',
    phone: '1 (937) 440-8126',
    email: 'SLoyd@MCVets.org',
    website: 'https://www.miamicountyohio.gov/veterans-services/',
  },
  Monroe: {
    officeName: 'Monroe County Veterans Service Office',
    address: '118 Home Ave., Box 542, Woodsfield, OH 43793',
    phone: '1 (740) 472-0743',
    email: 'monroe.veterans@monroecountyohio.com',
    website: 'https://monroeveterans.org/',
  },
  Montgomery: {
    officeName: 'Montgomery County Veterans Service Office',
    address: '627 Edwin C. Moses Blvd., 4th Flr., E. Medical Plaza, Dayton, OH 45417',
    phone: '1 (937) 225-4801',
    email: 'veteransinfo@mcohio.org',
    website: 'http://www.mcvsc.org/',
  },
  Morgan: {
    officeName: 'Morgan County Veterans Service Office',
    address: '135 S. Kennebec Ave., McConnelsville, OH 43756',
    phone: '1 (740) 962-4181',
    email: 'director@morganvso.com',
    website: 'https://www.morgancounty-oh.gov/veterans.html',
  },
  Morrow: {
    officeName: 'Morrow County Veterans Service Office',
    address: '143 S. Main St., Mount Gilead, OH 43338',
    phone: '1 (419) 946-1914',
    email: 'Vets@morrowcountyveterans.com',
    website: 'https://morrowcountyveterans.com',
  },
  Muskingum: {
    officeName: 'Muskingum County Veterans Service Office',
    address: '225 Underwood St., Ste. 500, Zanesville, OH 43701',
    phone: '1 (740) 455-7149',
    email: 'catouvell@muskingumcounty.org',
    website: 'https://www.muskingumcountyoh.gov/Agencies/Veterans/',
  },
  Noble: {
    officeName: 'Noble County Veterans Service Office',
    address: '190 Court House, Room 1A, Caldwell, OH 43724',
    phone: '1 (740) 732-5567',
    email: 'veterans@noblecountyohio.gov',
    website: 'https://noblecountyohio.gov/noble-county-veterans-service-commission',
  },
  Ottawa: {
    officeName: 'Ottawa County Veterans Service Office',
    address: '8444 W. State Rte. 163, Ste. 102, Oak Harbor, OH 43449',
    phone: '1 (419) 898-2089',
    email: 'veterans@co.ottawa.oh.us',
    website: 'https://www.co.ottawa.oh.us/358/Veterans-Service',
  },
  Paulding: {
    officeName: 'Paulding County Veterans Service Office',
    address: '810 E. Perry St., P.O. Box 215, Paulding, OH 45879',
    phone: '1 (419) 399-8285',
    email: 'jlichtyvso@pcohio.us',
    website: 'http://www.pauldingcountyoh.com/services/#veterans-services',
  },
  Perry: {
    officeName: 'Perry County Veterans Service Office',
    address: '128 S. Main St., New Lexington, OH 43764',
    phone: '1 (740) 342-2536',
    email: 'pcvets@perrycountyohio.gov',
    website: 'http://www.perrycountyohio.net/agencies-and-offices/perry-county-veterans-service-commission',
  },
  Pickaway: {
    officeName: 'Pickaway County Veterans Service Office',
    address: '141 W. Main St., Ste. 300, Circleville, OH 43113',
    phone: '1 (740) 474-3650',
    email: 'mpettibone@pickawaycountyohio.gov',
    website: 'https://pickawaycountyohio.gov/offices/veterans-assistance/index.html',
  },
  Pike: {
    officeName: 'Pike County Veterans Service Office',
    address: '120 S. Market St., Waverly, OH 45690',
    phone: '1 (740) 947-2766',
    email: 'pcvso@yahoo.com',
    website: 'https://dvs.ohio.gov/static/cvso-resources/cvso-pdf-webpages/pike-county-veterans-service-office.pdf',
  },
  Portage: {
    officeName: 'Portage County Veterans Service Office',
    address: '466 S. Chestnut St., Ravenna, OH 44266',
    phone: '1 (330) 297-3545',
    email: 'portageveterans@portageco.com',
    website: 'https://www.co.portage.oh.us/veterans-services',
  },
  Preble: {
    officeName: 'Preble County Veterans Service Office',
    address: '1322 N. Barron St., Eaton, OH 45320',
    phone: '1 (937) 456-6111',
    email: 'preblevso@woh.rr.com',
    website: 'https://preblecountyveterans.org/',
  },
  Putnam: {
    officeName: 'Putnam County Veterans Service Office',
    address: '336 E. Main St., Ste. A, Ottawa, OH 45875',
    phone: '1 (419) 523-4478',
    email: 'matt.prenzlin@putnamcountyohio.gov',
    website: 'https://www.pcvsc.org/',
  },
  Richland: {
    officeName: 'Richland County Veterans Service Office',
    address: '597 Park Ave. E., Mansfield, OH 44905',
    phone: '1 (419) 774-5822',
    email: 'info@richlandcountyvets.org',
    website: 'http://www.richlandcountyvets.org/',
  },
  Ross: {
    officeName: 'Ross County Veterans Service Office',
    address: 'The Ross County Service Center, 475 Western Ave., Ste. #C, Chillicothe, OH 45601',
    phone: '1 (740) 772-1600',
    email: 'nicolecharity@rosscountyohio.gov',
    website: 'https://www.rosscountyohio.gov/veterans/index.html',
  },
  Sandusky: {
    officeName: 'Sandusky County Veterans Service Office',
    address: '2511 Countryside Dr., Ste. B, Fremont, OH 43420',
    phone: '1 (419) 334-4421',
    email: 'tstanforth@sanduskycountyoh.gov',
    website: 'https://www.sandusky-county.com/index.php?page=veterans-office',
  },
  Scioto: {
    officeName: 'Scioto County Veterans Service Office',
    address: '612 6th St., Ste. A, Portsmouth, OH 45662',
    phone: '1 (740) 353-1477',
    email: 'wdillonscvso@yahoo.com',
    website: 'https://dvs.ohio.gov/static/cvso-resources/cvso-pdf-webpages/scioto-county-veterans-service-office.pdf',
  },
  Seneca: {
    officeName: 'Seneca County Veterans Service Office',
    address: '920 E. County Rd. 20, Tiffin, OH 44883',
    phone: '1 (419) 447-2885',
    email: 'sencotsb@bright.net',
    website: 'http://www.senecacountyveterans.org/',
  },
  Shelby: {
    officeName: 'Shelby County Veterans Service Office',
    address: '133 S. Ohio Ave., Sidney, OH 45365',
    phone: '1 (937) 498-7282',
    email: 'Sherrye.lamma@shelbycountyveterans.org',
    website: 'https://shelbycountyveterans.org/',
  },
  Stark: {
    officeName: 'Stark County Veterans Service Office',
    address: '2955 Wise Ave. NW, Canton, OH 44708',
    phone: '1 (330) 451-7457',
    email: 'dmwilliams@starkcountyohio.gov',
    website: 'https://www.starkcountyohio.gov/veterans',
  },
  Summit: {
    officeName: 'Summit County Veterans Service Office',
    address: '1060 E. Waterloo Rd., Akron, OH 44306',
    phone: '1 (330) 643-2830',
    email: 'lmoore@vscsummitoh.us',
    website: 'https://www.vscsummitoh.us/',
  },
  Trumbull: {
    officeName: 'Trumbull County Veterans Service Office',
    address: '253 E. Market St., Warren, OH 44481',
    phone: '1 (330) 675-2585',
    email: 'Trumbullcountyvets@co.trumbull.oh.us',
    website: 'http://veterans.co.trumbull.oh.us/',
  },
  Tuscarawas: {
    officeName: 'Tuscarawas County Veterans Service Office',
    address: '393 16th St. SW, P.O. Box 807, New Philadelphia, OH 44663',
    phone: '1 (330) 339-1163',
    email: 'cookd@co.tuscarawas.oh.us',
    website: 'https://www.co.tuscarawas.oh.us/government/veteran_services/index.php',
  },
  Union: {
    officeName: 'Union County Veterans Service Office',
    address: '835 E. Fifth St., Ste. B, Marysville, OH 43040',
    phone: '1 (937) 642-7956',
    email: 'ucvets@co.union.oh.us',
    website: 'https://www.unioncountyohio.gov/veterans',
  },
  'Van Wert': {
    officeName: 'Van Wert County Veterans Service Office',
    address: '121 E. Main St., Room 101, Van Wert, OH 45891',
    phone: '1 (419) 238-9592',
    email: 'vwvets@vanwertcounty.org',
    website: 'https://www.vanwertcountyohio.gov/services/veterans_services/index.php',
  },
  Vinton: {
    officeName: 'Vinton County Veterans Service Office',
    address: 'Courthouse, P.O. Box 63, McArthur, OH 45651',
    phone: '1 (740) 790-7043',
    email: 'veterans@vintonco.com',
    website: 'https://vintoncounty.com/government/elected-officials-departments/',
  },
  Warren: {
    officeName: 'Warren County Veterans Service Office',
    address: '320 E. Silver St., Lebanon, OH 45036',
    phone: '1 (513) 695-2717',
    email: 'John.agenbroad@co.warren.oh.us',
    website: 'http://www.warrencountyveterans.com/',
  },
  Washington: {
    officeName: 'Washington County Veterans Service Office',
    address: '706 Pike St., Ste. 1, Marietta, OH 45750',
    phone: '1 (740) 568-9009',
    email: 'darren.shearlock@wcvsc.com',
    website: 'https://www.washingtongov.org/162/Veteran-Services',
  },
  Wayne: {
    officeName: 'Wayne County Veterans Service Office',
    address: '356 W. North St., Lower Level, Wooster, OH 44691',
    phone: '1 (330) 345-6638',
    email: 'mail@WayneCountyVeterans.org',
    website: 'https://woosterchamber.chambermaster.com/list/member/wayne-county-veterans-service-commission-7607',
  },
  Williams: {
    officeName: 'Williams County Veterans Service Office',
    address: '1425 E. High St., Ste. 106, Bryan, OH 43506',
    phone: '1 (419) 636-8812',
    email: 'danielbonney@williamsvets.org',
    website: 'http://co.williams.oh.us/207/Veteran-Services',
  },
  Wood: {
    officeName: 'Wood County Veterans Service Office',
    address: '1940 E. Gypsy Lane Rd., Bowling Green, OH 43402',
    phone: '1 (419) 354-9147',
    email: 'zmigura@woodcountyohio.gov',
    website: 'https://www.woodcountyvets.com',
  },
  Wyandot: {
    officeName: 'Wyandot County Veterans Service Office',
    address: '250 Highland Parkway, Ste. B, Upper Sandusky, OH 43351',
    phone: '1 (419) 294-2045',
    email: 'wyandotcovets@co.wyandot.oh.us',
    website: 'http://www.wyandotveterans.org/',
  },
};

// Matches a typed free-text answer against the 88 county names (whole-word,
// case-insensitive) or common "not sure / not in Ohio" phrasing. Cosmetic
// keyword matching, same spirit as matchCategoryFromText in questions.js.
export function matchCountyFromText(text) {
  const normalized = text.toLowerCase();
  const county = OHIO_COUNTIES.find((name) => {
    const pattern = new RegExp(`\\b${name.toLowerCase()}\\b`);
    return pattern.test(normalized);
  });
  if (county) return county;
  if (/not sure|don't live in ohio|not in ohio|not from ohio|no idea/.test(normalized)) {
    return NOT_IN_OHIO;
  }
  return null;
}

const ODVS_STATEWIDE_PHONE = '(614) 644-0898';

export function getCvsoInfo(county) {
  if (county && CVSO_DIRECTORY[county]) {
    return CVSO_DIRECTORY[county];
  }
  const label = county && county !== NOT_IN_OHIO ? `${county} County` : 'Your local county';
  return {
    officeName: `${label} Veterans Service Office`,
    phone: ODVS_STATEWIDE_PHONE,
    address: null,
    email: null,
    website: null,
  };
}
